= Grype scan and publish to Platform

Use this action to perform static application security testing (SAST) on a repository with the Grype scanner, and then view comprehensive security results in the CloudBees platform.

== Prerequisites

Set up the CloudBees platform and GHA to work together, providing key features of the platform to GHA workflows. Refer to link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/github-actions/gha-getting-started[Getting started with GHA integration] for more information.

== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===

| Input name
| Data type
| Required?
| Description

| `cloudbees-pat`
| String
| Yes
| The https://docs.cloudbees.com/docs/cloudbees-platform/latest/workflows/personal-access-token[CloudBees platform personal access token].


| `cloudbees-url`
| String
| No
| The CloudBees platform URL. The default value is `https://api.cloudbees.io`.

| `binary-tar-path`
| String
| Yes
| Specify the path of the binary that should be scanned.

|===

== Usage examples

The following is a basic example of using this action:

[source,yaml]
----

      - name: Scan with Grype
        uses: https://github.com/cloudbees-io/grype-scan-publish@v1
        with:
          cloudbees-pat: ${{ secrets.CloudBees-platform-PAT }}
          binary-tar-path: tar file path that needs to be scanned

----


=== Full workflow and run example

The following GHA workflow example scans a repository with Grype.

.Example GHA workflow YAML file
[.collapsible]
--

[source, yaml,role="default-expanded"]
----
name: Grype scan workflow

on:
  push:
    branches:
    - main

jobs:
  Grype-codescan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Grype scan
        uses: cloudbees-io-gha/grype-scan-publish@v1
        with:
          cloudbees-pat: ${{ secrets.CLOUDBEES_PAT }}
          binary-tar-path: tar file path that needs to be scanned

----
--

After the GHA run has completed, the security findings are collected and displayed in the CloudBees platform https://docs.cloudbees.com/docs/cloudbees-platform/latest/aspm/security-center[Security center] of the component containing the workflow.

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/github-actions/intro[Using GitHub Actions with the CloudBees platform].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/[the CloudBees platform].